/**
 * REQ-00527: PDF 格式化器（用户可读报告）
 */

class PdfFormatter {
  constructor() {
    this.name = 'pdf';
    this.mimeType = 'application/pdf';
  }

  async format(data) {
    // 生成简单的 HTML 报告，可后续用 Puppeteer 转换为 PDF
    const html = this._generateHtmlReport(data);
    return Buffer.from(html, 'utf-8');
  }

  _generateHtmlReport(data) {
    const counts = data.export.recordCounts || {};
    
    return `<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>User Data Export - ${data.export.userId}</title>
  <style>
    body { font-family: Arial, sans-serif; padding: 40px; }
    h1 { color: #333; }
    .summary { background: #f5f5f5; padding: 20px; margin: 20px 0; }
    .section { margin: 30px 0; }
    table { width: 100%; border-collapse: collapse; }
    th, td { border: 1px solid #ddd; padding: 8px; text-align: left; }
    th { background: #4CAF50; color: white; }
    .watermark { position: fixed; top: 50%; left: 50%; transform: translate(-50%, -50%) rotate(-45deg); font-size: 48px; color: rgba(200, 200, 200, 0.3); pointer-events: none; }
  </style>
</head>
<body>
  <div class="watermark">GDPR DATA EXPORT</div>
  <h1>User Data Export</h1>
  <div class="summary">
    <p><strong>User ID:</strong> ${data.export.userId}</p>
    <p><strong>Export Date:</strong> ${data.export.exportedAt}</p>
    <p><strong>Format:</strong> PDF Report</p>
    <p><strong>Data Types:</strong> ${data.export.dataTypes.join(', ')}</p>
  </div>
  ${Object.entries(counts).map(([type, count]) => 
    `<div class="section">
      <h2>${type}</h2>
      <p>Records: ${count}</p>
    </div>`
  ).join('')}
  <footer>
    <p><small>Generated by mineGo Data Exporter | Compliance: GDPR Article 20 (Right to data portability)</small></p>
  </footer>
</body>
</html>`;
  }

  getDescription() {
    return {
      name: this.name,
      mimeType: this.mimeType,
      description: 'Human-readable PDF report for user review',
      compliance: { gdpr: true }
    };
  }
}

module.exports = PdfFormatter;